// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAfuIczJ_3PzkpOLEZfa600zhhVmm44l8U',
    appId: '1:16264222565:web:3ea2d679dd2c092b5f738c',
    messagingSenderId: '16264222565',
    projectId: 'new-messaging-app-409b6',
    authDomain: 'new-messaging-app-409b6.firebaseapp.com',
    storageBucket: 'new-messaging-app-409b6.appspot.com',
    measurementId: 'G-J8ZGRQLMLE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDlp-yBOdyctRGVuP7UULWIBMag6mw8M7w',
    appId: '1:16264222565:android:ecad256e659c14e95f738c',
    messagingSenderId: '16264222565',
    projectId: 'new-messaging-app-409b6',
    storageBucket: 'new-messaging-app-409b6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvFAJPMFG9mWUW7ymf0QiM3tjTJ5PGnHc',
    appId: '1:16264222565:ios:6bcd2e349929aaa05f738c',
    messagingSenderId: '16264222565',
    projectId: 'new-messaging-app-409b6',
    storageBucket: 'new-messaging-app-409b6.appspot.com',
    iosBundleId: 'com.example.newMessagingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvFAJPMFG9mWUW7ymf0QiM3tjTJ5PGnHc',
    appId: '1:16264222565:ios:fb35afe18ee69edf5f738c',
    messagingSenderId: '16264222565',
    projectId: 'new-messaging-app-409b6',
    storageBucket: 'new-messaging-app-409b6.appspot.com',
    iosBundleId: 'com.example.newMessagingApp.RunnerTests',
  );
}
